#!/bin/bash

set -e

table_name="${1}"

function execute() {
    echo "${2}" | sqlite3 "${1}"
}

function task_usage() {
    sample_count_query="SELECT COUNT(*) FROM \`${table_name}\`;"
    job_count_query="SELECT COUNT(DISTINCT \`job ID\`) FROM \`${table_name}\`;"
    sample_count=$(execute "${1}" "${sample_count_query}")
    job_count=$(execute "${1}" "${job_count_query}")
    echo "${1}: ${sample_count} ${job_count}"
}

case "${table_name}" in
    'task_usage')
        ;;
    *)
        echo 'No table is given, or it is unknown.' && exit -1
        ;;
esac

for part_path in $(find ${table_name} -name '*.sqlite3' | sort); do
    ${table_name} "${part_path}"
done
